### ISSUE TITLE
No window controls

### ISSUE THREAD

**Issue by ghost** [GKFX/hide-ff-title-bar#2]
This only hides title bar, and not have additional buttons - close/minimize/maximize?

**Comment by GKFX** [comment]
That's correct. Firefox ships with hidden close/minimize/maximize buttons in the navigation bar as well as on the title bar. Previously, these were unhidden in CSS by extensions such as HTitle, but unfortunately WebExtensions aren't allowed to apply CSS to the browser any more. Fortunately, `userChrome.css` can: see http://kb.mozillazine.org/index.php?title=UserChrome.css for how to set it up. The following basic CSS gives you a close button only, as on GNOME 3; you can modify it yourself to show whichever buttons you want. HTitle [used to move `#window-controls` to a better location](https://github.com/seleznev/firefox-extension-htitle/blob/master/extension/chrome/content/HTitleWindowControls.js) but I don't think that's possible any more.
```css
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

@-moz-document url("chrome://browser/content/browser.xul") {
  window[sizemode="maximized"] #window-controls {
    display: -moz-box;
  }
  #minimize-button, #restore-button {
    display: none;
  }
  #close-button {
    height: 27px;
    width: 27px;
    margin-left: 2px;
  }
}
```
Personally, I don't use that bit of CSS; I prefer to close Firefox either by closing all my tabs, or using <kbd>Alt</kbd>+<kbd>F4</kbd>.
